name: on_background_message
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: ^13.1.0
  test_plugin:
    path: test_plugin
  mindbox:
    path: mindbox/mindbox

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0