name: mindbox_platform_interface
description: Mindbox platform interface.
version: 2.1.5
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-moscow/flutter-sdk/tree/master/mindbox_platform_interface
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1